# Generated by Django 3.2.13 on 2023-07-23 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cookTimeInMins',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='prepTimeInMins',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='totalTimeInMins',
            field=models.IntegerField(),
        ),
    ]
