# Generated by Django 3.2.13 on 2023-07-23 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20230723_1208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='srNo',
        ),
    ]
